[project]
name = "handle_attachment_tags"
version = "0.1.0"
description = "handles the acceptance of the attachment"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.38.8",
]
